editor = "nano"
commit_types = [
    "feat",
    "chore",
    "fix",
    "docs",
]

# Template for interactive commit message generation
# Available variables: {commit_number}, {commit_type}, {branch_name}, {message}, {date}, {time}, {author}, {email}
template = "[{commit_number}] ({commit_type} on {branch_name}) {message}"
