name: Build and Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build-linux:
        name: Build Linux Binary
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  profile: minimal

            - name: Build release binary
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release

            - name: Create archive
              run: |
                  VERSION=${GITHUB_REF#refs/tags/v}
                  mkdir -p release
                  cp target/release/rona release/
                  cd release
                  tar -czvf rona-${VERSION}-linux-x86_64.tar.gz rona
                  cd ..

            - name: Generate Release Body
              run: |
                  cp .github/workflows/release_body.md release_body.md
                  VERSION=${GITHUB_REF#refs/tags/v}
                  sed -i.bak "s/\${GITHUB_REF#refs\/tags\/v}/${VERSION}/g" release_body.md

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: release/rona-*-linux-x86_64.tar.gz
                  body_path: release_body.md
                  generate_release_notes: true
                  append_body: true

    build-macos-intel:
        name: Build macOS Intel Binary
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  profile: minimal
                  target: x86_64-apple-darwin

            - name: Build release binary
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --target x86_64-apple-darwin

            - name: Create archive
              run: |
                  VERSION=${GITHUB_REF#refs/tags/v}
                  mkdir -p release
                  cp target/x86_64-apple-darwin/release/rona release/
                  cd release
                  tar -czvf rona-${VERSION}-macos-x86_64.tar.gz rona
                  cd ..

            - name: Calculate SHA256
              run: |
                  VERSION=${GITHUB_REF#refs/tags/v}
                  cd release
                  SHA256=$(shasum -a 256 rona-${VERSION}-macos-x86_64.tar.gz | cut -d ' ' -f 1)
                  echo "SHA256_INTEL=${SHA256}" >> $GITHUB_ENV
                  echo "### SHA256 (Intel)"  > sha256.md
                  echo '```' >> sha256.md
                  echo "${SHA256}  rona-${VERSION}-macos-x86_64.tar.gz" >> sha256.md
                  echo '```' >> sha256.md

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: release/rona-*-macos-x86_64.tar.gz
                  body_path: release/sha256.md
                  append_body: true

    build-macos-arm:
        name: Build macOS Apple Silicon Binary
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  profile: minimal
                  target: aarch64-apple-darwin

            - name: Build release binary
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --target aarch64-apple-darwin

            - name: Create archive
              run: |
                  VERSION=${GITHUB_REF#refs/tags/v}
                  mkdir -p release
                  cp target/aarch64-apple-darwin/release/rona release/
                  cd release
                  tar -czvf rona-${VERSION}-macos-arm64.tar.gz rona
                  cd ..

            - name: Calculate SHA256
              run: |
                  VERSION=${GITHUB_REF#refs/tags/v}
                  cd release
                  SHA256=$(shasum -a 256 rona-${VERSION}-macos-arm64.tar.gz | cut -d ' ' -f 1)
                  echo "SHA256_ARM=${SHA256}" >> $GITHUB_ENV
                  echo "### SHA256 (Apple Silicon)" > sha256.md
                  echo '```' >> sha256.md
                  echo "${SHA256}  rona-${VERSION}-macos-arm64.tar.gz" >> sha256.md
                  echo '```' >> sha256.md

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: release/rona-*-macos-arm64.tar.gz
                  body_path: release/sha256.md
                  append_body: true
